### ISSUE TITLE
Don't set max-height on inline suggestions

### ISSUE THREAD

**Issue by tvararu** [alphagov/accessible-typeahead#94]
Add this:

```css
.typeahead__menu--inline {
  max-height: none;
  overflow-x: visible;
}
```
